"""SQLite audit substrate — compatibility facade over storage and read model.

The audit substrate at ``.forge/audits/index.sqlite`` used to be one module
holding four change-reasons: schema definition, schema migration, record
persistence, and analytics. Those are now two owners with a named interface
between them (#2350):

``theforge.coordinator.audit_storage``
    Owns the substrate as *stored state*: connection opening and validation,
    ``_SCHEMA`` / ``_apply_schema``, ``SUBSTRATE_SCHEMA_VERSION`` and the
    re-index passes a bump implies, the sequential ``_migrate_vN_to_vN+1``
    catalogue with its ``MIGRATION_HELPERS`` registry and record decoders, and
    every write path (``upsert_run_record``, ``rebuild_from_runs``,
    ``import_history_jsonl``, the ``record_*`` event writers, ``seed_records``).
    The migration catalogue is one uninterrupted unit there and stays that way —
    it is meant to be read in order.

``theforge.coordinator.audit_read_model``
    Owns the substrate as a *queryable model*: the SELECT queries and the
    derivations built on them. It depends on storage through
    ``audit_storage.AuditConnection`` — a connection storage has opened,
    validated, and brought to the current schema — and issues SELECT SQL
    against one directly. It calls storage's ``_load_migrated`` when it needs
    the decoded record, so record migration stays storage's responsibility.

The dependency runs one way: storage never imports the read model. That is what
makes a new analytical query and a new record migration independent changes —
neither touches the other's file, and the scheduler no longer sees them as one
file claim.

This module re-exports both halves, including the private names other modules
and tests import, so every existing ``from ...audit_substrate import X`` keeps
working. New code should import from the owning module instead. Note that
``monkeypatch.setattr`` against a name here rebinds only this facade's
reference — patch the owning module when a seam needs replacing.
"""

from __future__ import annotations

# ── Read model: analytical queries and derivations ───────────────────────
from .audit_read_model import (  # noqa: F401
    _COMPLEXITY_BAND_NORMALIZE,
    _COMPLEXITY_TO_BAND,
    _coerce_complexity_score,
    _derive_escalation,
    _normalize_complexity_band,
    alias_resolution_timeline,
    count_records,
    derive_assignment_history,
    derive_cost_samples_by_score,
    derive_observed_cost_cohorts,
    has_review_approve_in_substrate,
    inline_remediation_rollup_by_milestone,
    iter_escalation_records,
    iter_inline_remediation_events,
    iter_invocation_identities,
    iter_readiness_events,
    iter_records,
    iter_shape_skip_events,
    iter_shape_verdict_events,
    iter_triage_application_records,
    iter_triage_proposal_events,
    landed_run_ids_in_substrate,
    landing_projection_status,
    landing_state_for_run,
    landing_states,
    latest_record_for,
    latest_run_outcome_in_substrate,
    load_observed_cost_cohorts,
    load_triage_proposal_run,
    lookup_recorded_configuration_value,
    repeated_shape_skip_blocks,
    runs_touching_path,
    tail_records,
    triage_disposition_history,
    triage_proposal_run_spend,
    verdict_outcome_counts,
)

# ── Storage: connection, schema, migrations, writes ──────────────────────
# The migration catalogue, re-exported in sequence.
from .audit_storage import (  # noqa: F401  # noqa: F401
    _CHANGED_FILE_COLUMNS,
    _DEV_IDENTITY_COLUMNS,
    _INVOCATION_IDENTITY_COLUMNS,
    _SCHEMA,
    _SHAPE_SKIP_SNAPSHOT_COLUMNS,
    AUDIT_PATH_REGISTRY,
    AUDITS_RELPATH,
    CURRENT_RECORD_SCHEMA_VERSION,
    HISTORY_RELPATH,
    LANDING_PROJECTION_FINGERPRINT_KEY,
    LANDING_PROJECTION_SOURCE_COUNT_KEY,
    LANDING_PROJECTION_SYNCED_AT_KEY,
    MIGRATION_HELPERS,
    RUNS_RELPATH,
    SECRETS_RELPATH,
    SKIP_STATUS_NO_PRIOR,
    SKIP_STATUS_STILL_BLOCKED,
    SKIP_STATUS_UNBLOCKED,
    SUBSTRATE_RELPATH,
    SUBSTRATE_SCHEMA_VERSION,
    AuditConnection,
    AuditPathInfo,
    ImportSummary,
    RebuildSummary,
    SubstrateCorruptError,
    SubstrateError,
    SubstrateLockTimeoutError,
    SubstrateMissingError,
    UpsertResult,
    _apply_schema,
    _canonical_json,
    _changed_file_params,
    _derive_record_verdict,
    _dev_identity_columns,
    _extract_reviews,
    _flat_fields,
    _import_history_classify,
    _import_history_jsonl_into,
    _invocation_identity_params,
    _load_migrated,
    _meta_get,
    _meta_set,
    _migrate_record,
    _migrate_v1_to_v2,
    _migrate_v2_to_v3,
    _migrate_v3_to_v4,
    _migrate_v4_to_v5,
    _migrate_v5_to_v6,
    _migrate_v6_to_v7,
    _migrate_v7_to_v8,
    _migrate_v8_to_v9,
    _migrate_v9_to_v10,
    _migrate_v10_to_v11,
    _migrate_v11_to_v12,
    _migrate_v12_to_v13,
    _migrate_v13_to_v14,
    _migrate_v14_to_v15,
    _migrate_v15_to_v16,
    _migrate_v16_to_v17,
    _migrate_v17_to_v18,
    _migrate_v18_to_v19,
    _migrate_v19_to_v20,
    _migrate_v20_to_v21,
    _migrate_v21_to_v22,
    _migrate_v22_to_v23,
    _migrate_v23_to_v24,
    _migrate_v24_to_v25,
    _migrate_v25_to_v26,
    _migrate_v26_to_v27,
    _migrate_v27_to_v28,
    _migrate_v28_to_v29,
    _migrate_v29_to_v30,
    _migrate_v30_to_v31,
    _migrate_v31_to_v32,
    _migrate_v32_to_v33,
    _migrate_v33_to_v34,
    _migrate_v34_to_v35,
    _migrate_v35_to_v36,
    _migrate_v36_to_v37,
    _migrate_v37_to_v38,
    _migrate_v38_to_v39,
    _migrate_v39_to_v40,
    _migrate_v40_to_v41,
    _migrate_v41_to_v42,
    _migrate_v42_to_v43,
    _migrate_v43_to_v44,
    _native_rows_are_stale,
    _now_iso,
    _open_validated,
    _reindex_changed_files,
    _reindex_dev_model_identity,
    _reindex_invocation_identities,
    _restore_shape_skip_events,
    _skip_last_status,
    _skip_prior_block_history,
    _snapshot_shape_skip_events,
    _stored_schema_version,
    _write_changed_files,
    _write_invocation_identities,
    audits_dir,
    create_or_open,
    derive_run_id,
    has_audit_inputs,
    history_jsonl_path,
    import_history_jsonl,
    open_readonly,
    rebuild_from_runs,
    record_inline_remediation_event,
    record_readiness_event,
    record_shape_skip_event,
    record_shape_verdict_event,
    record_triage_proposal_event,
    record_triage_proposal_run,
    require_substrate,
    runs_dir,
    secrets_env_path,
    seed_records,
    substrate_path,
    sync_landing_evidence,
    upsert_run_record,
    upsert_triage_application_record,
)

__all__ = [
    "_apply_schema",
    "_canonical_json",
    "_CHANGED_FILE_COLUMNS",
    "_changed_file_params",
    "_coerce_complexity_score",
    "_COMPLEXITY_BAND_NORMALIZE",
    "_COMPLEXITY_TO_BAND",
    "_derive_escalation",
    "_derive_record_verdict",
    "_dev_identity_columns",
    "_DEV_IDENTITY_COLUMNS",
    "_extract_reviews",
    "_flat_fields",
    "_import_history_classify",
    "_import_history_jsonl_into",
    "_INVOCATION_IDENTITY_COLUMNS",
    "_invocation_identity_params",
    "_load_migrated",
    "_meta_get",
    "_meta_set",
    "_migrate_record",
    "_migrate_v10_to_v11",
    "_migrate_v11_to_v12",
    "_migrate_v12_to_v13",
    "_migrate_v13_to_v14",
    "_migrate_v14_to_v15",
    "_migrate_v15_to_v16",
    "_migrate_v16_to_v17",
    "_migrate_v17_to_v18",
    "_migrate_v18_to_v19",
    "_migrate_v19_to_v20",
    "_migrate_v1_to_v2",
    "_migrate_v20_to_v21",
    "_migrate_v21_to_v22",
    "_migrate_v22_to_v23",
    "_migrate_v23_to_v24",
    "_migrate_v24_to_v25",
    "_migrate_v25_to_v26",
    "_migrate_v26_to_v27",
    "_migrate_v27_to_v28",
    "_migrate_v28_to_v29",
    "_migrate_v29_to_v30",
    "_migrate_v30_to_v31",
    "_migrate_v31_to_v32",
    "_migrate_v32_to_v33",
    "_migrate_v33_to_v34",
    "_migrate_v34_to_v35",
    "_migrate_v35_to_v36",
    "_migrate_v36_to_v37",
    "_migrate_v37_to_v38",
    "_migrate_v38_to_v39",
    "_migrate_v39_to_v40",
    "_migrate_v40_to_v41",
    "_migrate_v41_to_v42",
    "_migrate_v42_to_v43",
    "_migrate_v43_to_v44",
    "_migrate_v2_to_v3",
    "_migrate_v3_to_v4",
    "_migrate_v4_to_v5",
    "_migrate_v5_to_v6",
    "_migrate_v6_to_v7",
    "_migrate_v7_to_v8",
    "_migrate_v8_to_v9",
    "_migrate_v9_to_v10",
    "_native_rows_are_stale",
    "_normalize_complexity_band",
    "_now_iso",
    "_open_validated",
    "_reindex_changed_files",
    "_reindex_dev_model_identity",
    "_reindex_invocation_identities",
    "_restore_shape_skip_events",
    "_SCHEMA",
    "_SHAPE_SKIP_SNAPSHOT_COLUMNS",
    "_skip_last_status",
    "_skip_prior_block_history",
    "_snapshot_shape_skip_events",
    "_stored_schema_version",
    "_write_changed_files",
    "_write_invocation_identities",
    "alias_resolution_timeline",
    "AUDIT_PATH_REGISTRY",
    "AuditConnection",
    "AuditPathInfo",
    "audits_dir",
    "AUDITS_RELPATH",
    "count_records",
    "create_or_open",
    "CURRENT_RECORD_SCHEMA_VERSION",
    "derive_assignment_history",
    "derive_cost_samples_by_score",
    "derive_observed_cost_cohorts",
    "derive_run_id",
    "has_audit_inputs",
    "has_review_approve_in_substrate",
    "history_jsonl_path",
    "HISTORY_RELPATH",
    "import_history_jsonl",
    "ImportSummary",
    "inline_remediation_rollup_by_milestone",
    "iter_escalation_records",
    "iter_inline_remediation_events",
    "iter_invocation_identities",
    "iter_readiness_events",
    "iter_records",
    "iter_shape_skip_events",
    "iter_shape_verdict_events",
    "iter_triage_application_records",
    "iter_triage_proposal_events",
    "landed_run_ids_in_substrate",
    "LANDING_PROJECTION_FINGERPRINT_KEY",
    "LANDING_PROJECTION_SOURCE_COUNT_KEY",
    "LANDING_PROJECTION_SYNCED_AT_KEY",
    "landing_projection_status",
    "landing_state_for_run",
    "landing_states",
    "latest_record_for",
    "latest_run_outcome_in_substrate",
    "load_observed_cost_cohorts",
    "load_triage_proposal_run",
    "MIGRATION_HELPERS",
    "open_readonly",
    "rebuild_from_runs",
    "RebuildSummary",
    "record_inline_remediation_event",
    "record_readiness_event",
    "record_shape_skip_event",
    "record_shape_verdict_event",
    "record_triage_proposal_event",
    "record_triage_proposal_run",
    "repeated_shape_skip_blocks",
    "require_substrate",
    "runs_dir",
    "RUNS_RELPATH",
    "runs_touching_path",
    "secrets_env_path",
    "SECRETS_RELPATH",
    "seed_records",
    "SKIP_STATUS_NO_PRIOR",
    "SKIP_STATUS_STILL_BLOCKED",
    "SKIP_STATUS_UNBLOCKED",
    "substrate_path",
    "SUBSTRATE_RELPATH",
    "SUBSTRATE_SCHEMA_VERSION",
    "SubstrateCorruptError",
    "SubstrateError",
    "SubstrateLockTimeoutError",
    "SubstrateMissingError",
    "sync_landing_evidence",
    "tail_records",
    "triage_disposition_history",
    "triage_proposal_run_spend",
    "upsert_triage_application_record",
    "upsert_run_record",
    "UpsertResult",
    "verdict_outcome_counts",
]
