"""forge init / secrets-init / version subcommands."""

from __future__ import annotations

import argparse
import importlib.metadata
import json
import subprocess
import sys
from pathlib import Path

from theforge.config import PROVIDER_API_KEY_MAP, generate_default_config

# ── Canonical .gitignore / .gitattributes templates ──────────────────
#
# `forge init` and `forge secrets-init` share these template builders so
# there is exactly one source of truth for the block TheForge writes.
#
# The .gitignore block is default-deny: it ignores everything under
# `.forge/` and explicitly re-includes the paths that are project memory
# (tracked audit runs + knowledge summaries) and config (hooks,
# `.env.example`). Default-deny fails closed — a future TheForge version
# that ships a new subdirectory under `.forge/` defaults to ignored rather
# than accidentally-tracked. See docs/plans/forge-storage-layout.md,
# "The Canonical .gitignore Block".

# Marker lines used to detect an existing TheForge block (for idempotency
# and drift detection). They frame both the .gitignore and .gitattributes
# blocks; each file carries at most one block.
_TF_BLOCK_START = "# ── TheForge ──────────────────────────────────────────────────────────"
_TF_BLOCK_END = "# ──────────────────────────────────────────────────────────────────────"

_GITIGNORE_COMMENT = """\
# TheForge writes everything under .forge/. We deny the whole directory
# by default and explicitly re-include the paths that are project memory
# (tracked, travel with the repo) and config (tracked, travel with the
# repo). Everything else — secrets, runtime state, derived views — stays
# local to your machine.
#
# To opt out of shared memory entirely (public repo, stricter data
# boundary), run `forge init --local-memory` or delete the project-memory
# re-includes below (the `audits/` and `knowledge/summaries/` lines —
# keep the hooks and .env.example re-includes, those are config).
#
# See: docs/plans/forge-storage-layout.md"""

_GITIGNORE_DENY = """\
# Deny everything under .forge/ by default
.forge/**"""

_GITIGNORE_MEMORY_REINCLUDES = """\
# Re-include project memory (canonical per-run records)
!.forge/audits/
!.forge/audits/runs/
!.forge/audits/runs/**
!.forge/audits/landing/
!.forge/audits/landing/**
!.forge/knowledge/
!.forge/knowledge/summaries/
!.forge/knowledge/summaries/**"""

_GITIGNORE_CONFIG_REINCLUDES = """\
# Re-include config
!.forge/hooks/
!.forge/hooks/**
!.forge/.env.example"""

_GITIGNORE_ROOT = """\
# Root-level runtime state — always ignored
handoff.yaml"""

_GITATTRIBUTES_BODY = """\
# Audit runs and knowledge summaries are generated by TheForge. Collapse
# them in PR diffs so reviewers focus on source changes.
.forge/audits/runs/**  linguist-generated=true
.forge/audits/landing/**  linguist-generated=true
.forge/knowledge/summaries/**  linguist-generated=true"""


def _gitignore_block(*, shared_memory: bool) -> str:
    """Return the canonical TheForge .gitignore block.

    With *shared_memory* (the default), the project-memory re-includes are
    present so audit runs and knowledge summaries travel with the repo. With
    ``shared_memory=False`` (``forge init --local-memory``) those re-includes
    are omitted — the deny rule and the config re-includes stay.
    """
    sections = [_GITIGNORE_COMMENT, "", _GITIGNORE_DENY, ""]
    if shared_memory:
        sections += [_GITIGNORE_MEMORY_REINCLUDES, ""]
    sections += [_GITIGNORE_CONFIG_REINCLUDES, "", _GITIGNORE_ROOT]
    body = "\n".join(sections)
    return f"{_TF_BLOCK_START}\n{body}\n{_TF_BLOCK_END}"


def _gitattributes_block() -> str:
    """Return the canonical TheForge .gitattributes block.

    Written regardless of the memory mode — it is harmless when nothing is
    tracked and collapses per-run diffs for projects that do track memory.
    """
    return f"{_TF_BLOCK_START}\n{_GITATTRIBUTES_BODY}\n{_TF_BLOCK_END}"


_STORY_TEMPLATE = """\
---
# Story frontmatter — required fields
name: "Short human-readable title"
slug: my-feature-slug        # used for branch and worktree names
---

# Story title

## Problem / context

One paragraph explaining WHY this change is needed and WHAT problem it solves.
Background and motivation belong here. This section is informational — it is
NOT a list of requirements.

## Acceptance criteria

<!--
  ACs are the definitive checklist. The dev agent will implement exactly what
  is stated here. Write them as observable, testable behaviors.
  Each AC should be a single bullet starting with a verb.
-->

- The system does X when Y
- Existing tests continue to pass
- New test verifies Z

## Notes (optional)

Any additional context, constraints, or design guidance. The dev agent will
read this as context, not as requirements.
"""


def _extract_forge_block(content: str) -> str | None:
    """Return the existing TheForge marker block from *content*, or None.

    A block is the run of lines from ``_TF_BLOCK_START`` to the first
    following ``_TF_BLOCK_END``. A start marker with no matching end marker
    returns everything from the start onward, which will not match either
    canonical variant and is therefore treated as drift by the caller.
    """
    lines = content.splitlines()
    start = None
    for i, line in enumerate(lines):
        if line == _TF_BLOCK_START:
            start = i
            break
    if start is None:
        return None
    for j in range(start + 1, len(lines)):
        if lines[j] == _TF_BLOCK_END:
            return "\n".join(lines[start : j + 1])
    return "\n".join(lines[start:])


def _write_forge_block(path: Path, block: str, known_good: set[str]) -> str:
    """Idempotently write *block* into *path*, detecting drift.

    Returns one of:
    - ``"written"``  — the block was appended (or the file was created)
    - ``"current"``  — an existing block already matches a canonical variant
    - ``"drift"``    — an existing block differs from every canonical variant;
                        left untouched so user edits are not overwritten
    """
    content = path.read_text(encoding="utf-8") if path.exists() else ""
    existing = _extract_forge_block(content)
    if existing is not None:
        return "current" if existing in known_good else "drift"

    if content and not content.endswith("\n"):
        content += "\n"
    if content and not content.endswith("\n\n"):
        content += "\n"
    path.write_text(content + block + "\n", encoding="utf-8")
    return "written"


def _ensure_gitignored(project_root: Path, *, shared_memory: bool = True) -> str:
    """Write the canonical TheForge .gitignore block if not already present.

    Idempotent and drift-aware: an existing canonical block (in either the
    shared- or local-memory shape) is left alone; a block that has been
    edited away from both canonical shapes is surfaced as ``"drift"`` and
    not overwritten. Returns the status string from ``_write_forge_block``.
    """
    gitignore = project_root / ".gitignore"
    known_good = {
        _gitignore_block(shared_memory=True),
        _gitignore_block(shared_memory=False),
    }
    return _write_forge_block(gitignore, _gitignore_block(shared_memory=shared_memory), known_good)


def _ensure_gitattributes(project_root: Path) -> str:
    """Write the canonical TheForge .gitattributes block if not already present.

    Marks tracked audit runs and knowledge summaries as
    ``linguist-generated=true`` so GitHub collapses them in PR diffs.
    Idempotent and drift-aware; returns the ``_write_forge_block`` status.
    """
    gitattributes = project_root / ".gitattributes"
    block = _gitattributes_block()
    return _write_forge_block(gitattributes, block, {block})


def _report_template_status(kind: str, status: str) -> None:
    """Print a user-facing message for a template-write outcome."""
    if status == "written":
        print(f"Updated {kind} with the canonical TheForge block")
    elif status == "drift":
        print(
            f"⚠ {kind} has a TheForge block that differs from the canonical "
            f"template — leaving it untouched. Review it by hand (or remove the "
            f"block and re-run) if you want the current template.",
            file=sys.stderr,
        )


def _generate_secrets_skeleton() -> str:
    """Generate .env skeleton from PROVIDER_API_KEY_MAP."""
    lines = [
        "# .forge/.env — project-scoped secrets for TheForge",
        "# Copy this file to .forge/.env and fill in the values you need.",
        "# This file (.env.example) is tracked; .env is gitignored.",
        "",
    ]
    for _provider, key in PROVIDER_API_KEY_MAP.items():
        lines.append(f"# {key}=")
    lines.append("# NTFY_URL=https://ntfy.sh/your-topic-here")
    lines.append("")
    return "\n".join(lines)


def cmd_secrets_init(args: "argparse.Namespace") -> int:
    """Create .forge/.env skeleton and update .gitignore."""

    project_root = Path.cwd()
    env_path = project_root / ".forge" / ".env"
    secrets_yaml_path = project_root / ".forge" / "secrets.yaml"

    if secrets_yaml_path.exists() and not env_path.exists():
        print(
            "⚠ .forge/secrets.yaml detected — migrate to .forge/.env (see .forge/.env.example)",
            file=sys.stderr,
        )

    if env_path.exists():
        print(
            f"Warning: {env_path} already exists. Not overwriting.",
            file=sys.stderr,
        )
        return 0

    env_path.parent.mkdir(parents=True, exist_ok=True)
    env_path.write_text(_generate_secrets_skeleton(), encoding="utf-8")
    print(f"Created {env_path}")

    _report_template_status(".gitignore", _ensure_gitignored(project_root))
    _report_template_status(".gitattributes", _ensure_gitattributes(project_root))
    return 0


def _apply_git_templates(project_root: Path, *, shared_memory: bool) -> None:
    """Write (or drift-check) the canonical .gitignore/.gitattributes blocks."""
    _report_template_status(
        ".gitignore", _ensure_gitignored(project_root, shared_memory=shared_memory)
    )
    _report_template_status(".gitattributes", _ensure_gitattributes(project_root))


def cmd_init(args: "argparse.Namespace") -> int:
    """Generate a starter forge.yaml in the current directory."""

    project_root = Path.cwd()
    shared_memory = getattr(args, "shared_memory", True)

    target = project_root / "forge.yaml"
    if target.exists():
        print(f"forge.yaml already exists: {target}", file=sys.stderr)
        # Still validate the git templates on re-run so drift is surfaced and
        # missing blocks are written even though forge.yaml is left alone.
        _apply_git_templates(project_root, shared_memory=shared_memory)
        return 1

    target.write_text(generate_default_config(), encoding="utf-8")
    print(f"Created {target}")

    stories_dir = project_root / "stories"
    stories_dir.mkdir(exist_ok=True)
    template_path = stories_dir / "TEMPLATE.md"
    if not template_path.exists():
        template_path.write_text(_STORY_TEMPLATE, encoding="utf-8")
        print(f"Created {template_path}")

    print("Edit forge.yaml to match your project, then run: forge run <story-file>")

    _apply_git_templates(project_root, shared_memory=shared_memory)
    return 0


def _editable_source_path() -> str | None:
    """Return the filesystem path of the editable theforge checkout, or None.

    Reads direct_url.json (present only for editable/VCS installs) and
    converts the ``file://`` URL to an absolute path.  Returns None for
    PyPI installs or when the metadata is unavailable.
    """
    try:
        dist = importlib.metadata.distribution("theforge")
    except importlib.metadata.PackageNotFoundError:
        return None

    text = dist.read_text("direct_url.json")
    if not text:
        return None

    try:
        data = json.loads(text)
        url: str = data.get("url", "")
    except (json.JSONDecodeError, AttributeError):
        return None

    if not url.startswith("file://"):
        return None
    # file:///abs/path  →  /abs/path
    return url[len("file://") :]


def _get_dev_suffix(source_path: str | None = None) -> str:
    """Return '-dev+g<hash>' when editable install is ahead of the latest tag.

    Pass *source_path* (the editable checkout directory) to avoid a second
    call to ``_editable_source_path``.  Returns an empty string when:
    - not an editable install (no direct_url.json)
    - at exact tag (distance == 0)
    - git is unavailable
    """
    if source_path is None:
        source_path = _editable_source_path()
    if source_path is None:
        return ""

    try:
        # Output format: <tag>-<distance>-g<hash>  e.g. v0.2.1-5-g8704ff0
        describe = subprocess.check_output(
            ["git", "describe", "--tags", "--long"],
            text=True,
            stderr=subprocess.DEVNULL,
            cwd=source_path,
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError, OSError):
        return ""

    parts = describe.rsplit("-", 2)
    if len(parts) != 3:
        return ""
    _, distance_str, short_hash = parts
    try:
        distance = int(distance_str)
    except ValueError:
        return ""

    if distance == 0:
        return ""
    return f"-dev+{short_hash}"


def cmd_version(args: "argparse.Namespace") -> int:
    """Print the installed version of TheForge."""

    import theforge

    source_path = _editable_source_path()
    version = theforge.__version__ + _get_dev_suffix(source_path)
    print(f"TheForge version: {version}")

    if source_path is not None:
        # Try to get git info from the editable checkout
        try:
            branch = subprocess.check_output(
                ["git", "rev-parse", "--abbrev-ref", "HEAD"],
                text=True,
                stderr=subprocess.DEVNULL,
                cwd=source_path,
            ).strip()
            commit = subprocess.check_output(
                ["git", "rev-parse", "HEAD"],
                text=True,
                stderr=subprocess.DEVNULL,
                cwd=source_path,
            ).strip()
            tag_distance = subprocess.check_output(
                ["git", "describe", "--tags", "--long"],
                text=True,
                stderr=subprocess.DEVNULL,
                cwd=source_path,
            ).strip()
            print(f"  Branch: {branch}")
            print(f"  Commit: {commit}")
            print(f"  Tag distance: {tag_distance}")
        except (subprocess.CalledProcessError, FileNotFoundError, OSError):
            print("  (Git information not available)")

    return 0
