"""TheForge configuration package.

Re-exports the public API from sub-modules. Internal helpers
(underscore-prefixed symbols) are not re-exported here; import them
directly from their owning sub-modules (e.g. ``theforge.config.profiles``).
"""

from __future__ import annotations

from .defaults import (
    API_PROVIDER_DEFAULT_TOOLS,
    DEFAULT_DEV_PROFILE,
    DEFAULT_INVESTIGATION_TOOLS,
    DEFAULT_PREFLIGHT_PROFILE,
    DEFAULT_REVIEW_PROFILE,
    DEFAULT_VALIDATION,
    DEFAULT_WORKSPACE,
    PREFLIGHT_ALLOWED_CAPABILITIES,
    PREFLIGHT_FORBIDDEN_TOOLS,
    PREFLIGHT_READ_ONLY_TOOLS,
    PROVIDER_API_KEY_MAP,
    PROVIDER_SDK_MAP,
    SUPPORTED_CLIS,
    TRIAGE_PROPOSER_TOOLS,
    generate_default_config,
    resolve_preflight_tools,
)
from .gate_scrub import SCRUBBED_CLI_LAUNCHERS, SCRUBBED_ENV_VARS, SCRUBBED_HOME_PATHS
from .load import _validate_plan_provider, load_config
from .models import (
    AGENT_REGISTRY,
    MODEL_REGISTRY,
    AgentDef,
    AgentSpec,
    ModelInfo,
    RoutingPolicy,
    TransportSpec,
    apply_model_info,
    canonical_id_for_spec,
    canonical_model_id,
    is_canonical_model_id,
    model_info_view,
    normalize_model_key,
    provider_for_transport,
    resolve_agent_spec,
    transport_for,
)
from .provenance import (
    ConfigProvenance,
    build_provenance,
    resolved_config_sha256,
)
from .types import (
    DEFAULT_PREFLIGHT_COMPLEXITY_GATE_THRESHOLD,
    ESCALATE_TIMEOUT_APPLY_ADVICE,
    ESCALATE_TIMEOUT_POLICIES,
    ESCALATE_TIMEOUT_PRESERVE,
    PREFLIGHT_GATE_ACTIONS,
    PREFLIGHT_GATE_APPROVE,
    PREFLIGHT_GATE_DECOMPOSE,
    SUPPORTED_PROVIDERS,
    AdvisoryConventionsConfig,
    AdvisoryIssueFilingConfig,
    AssignmentConfig,
    BackendConfig,
    DevConfig,
    DevVerificationCommand,
    DiagnoseConfig,
    ExplorationConfig,
    FindingClassifierConfig,
    ForgeConfig,
    GithubConfig,
    HooksConfig,
    KnowledgeConfig,
    LogConfig,
    ModelProfile,
    ModelRef,
    NotificationConfig,
    NtfyConfig,
    PlanAgentReviewConfig,
    PlanConfig,
    PlanReviewConfig,
    ProviderReasoningEffortConfig,
    ReasoningEffortConfig,
    RecencyConfig,
    RetryPolicy,
    SandboxConfig,
    SlackConfig,
    SprintBatchConfig,
    SprintConfig,
    StuckDetectionConfig,
    TransportFallbackConfig,
    ValidationConfig,
    WorkspaceConfig,
    normalize_preflight_gate_no_decision,
)

__all__ = [
    # types
    "AgentDef",
    "AdvisoryConventionsConfig",
    "AdvisoryIssueFilingConfig",
    "TransportFallbackConfig",
    "AssignmentConfig",
    "BackendConfig",
    "ConfigProvenance",
    "DevConfig",
    "DevVerificationCommand",
    "DiagnoseConfig",
    "ExplorationConfig",
    "FindingClassifierConfig",
    "ForgeConfig",
    "GithubConfig",
    "HooksConfig",
    "KnowledgeConfig",
    "LogConfig",
    "ModelInfo",
    "ModelProfile",
    "ModelRef",
    "NotificationConfig",
    "NtfyConfig",
    "PlanAgentReviewConfig",
    "PlanConfig",
    "ProviderReasoningEffortConfig",
    "ReasoningEffortConfig",
    "PlanReviewConfig",
    "RecencyConfig",
    "RetryPolicy",
    "DEFAULT_PREFLIGHT_COMPLEXITY_GATE_THRESHOLD",
    "ESCALATE_TIMEOUT_APPLY_ADVICE",
    "ESCALATE_TIMEOUT_POLICIES",
    "ESCALATE_TIMEOUT_PRESERVE",
    "PREFLIGHT_GATE_ACTIONS",
    "PREFLIGHT_GATE_APPROVE",
    "PREFLIGHT_GATE_DECOMPOSE",
    "normalize_preflight_gate_no_decision",
    "SandboxConfig",
    "SlackConfig",
    "SprintBatchConfig",
    "SprintConfig",
    "StuckDetectionConfig",
    "SUPPORTED_PROVIDERS",
    "ValidationConfig",
    "WorkspaceConfig",
    # models / registry
    "AGENT_REGISTRY",
    "AgentSpec",
    "MODEL_REGISTRY",
    "RoutingPolicy",
    "TransportSpec",
    "apply_model_info",
    "canonical_id_for_spec",
    "canonical_model_id",
    "is_canonical_model_id",
    "model_info_view",
    "normalize_model_key",
    "provider_for_transport",
    "resolve_agent_spec",
    "transport_for",
    # defaults
    "API_PROVIDER_DEFAULT_TOOLS",
    "DEFAULT_DEV_PROFILE",
    "DEFAULT_INVESTIGATION_TOOLS",
    "DEFAULT_PREFLIGHT_PROFILE",
    "DEFAULT_REVIEW_PROFILE",
    "DEFAULT_VALIDATION",
    "DEFAULT_WORKSPACE",
    "PREFLIGHT_ALLOWED_CAPABILITIES",
    "PREFLIGHT_FORBIDDEN_TOOLS",
    "PREFLIGHT_READ_ONLY_TOOLS",
    "TRIAGE_PROPOSER_TOOLS",
    "PROVIDER_API_KEY_MAP",
    "PROVIDER_SDK_MAP",
    "SUPPORTED_CLIS",
    "generate_default_config",
    "resolve_preflight_tools",
    "SCRUBBED_CLI_LAUNCHERS",
    "SCRUBBED_ENV_VARS",
    "SCRUBBED_HOME_PATHS",
    # provenance (#2056)
    "build_provenance",
    "resolved_config_sha256",
    # load
    "_validate_plan_provider",
    "load_config",
]
